adding terraform scripts
OpenLXP/openlxp-infrastructure pull request #2
Opened 2021-02-02 23:26 UTC by micson-us

broke down terraform scripts

2021-02-03 00:17 UTC, mattdrayer requested changes
This is looking really great!  Mainly I just pointed out some inconsistencies and possibly invalid references -- we should be able to finish this PR up soon!

2021-02-03 00:17 UTC, mattdrayer commented on aws_xis_taskdefinition.tf
> +  family                = "dau_xis_task_definition"
Can remove `dau_` prefix from here, I think.

2021-02-03 00:17 UTC, mattdrayer commented on aws_xis_taskdefinition.tf
> +  family                = "dau_xis_task_definition"
remove `dau_`

2021-02-03 00:17 UTC, mattdrayer commented on aws_xse_taskdefinition.tf
> +# creates the XIA task definition. container definition is defined in the service.json file
XIA -> XSE

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_ecs_cluster.tf
> +resource "aws_ecs_cluster" "dau_xss_cluster" {
Remove `dau_`

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_ecs_cluster.tf
> +  name = "dau_xss_cluster"
Remove `dau_`

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_ecs_cluster.tf
> +resource "aws_ecs_service" "dau_xss_service" {
remove `dau_`

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_ecs_cluster.tf
> +  name            = "dau_xia"
-> `xss_ecs_service` -- does this need to align with the resource name?  seems like that would make sense.

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_ecs_cluster.tf
> +  cluster         = aws_ecs_cluster.dau_xss_cluster.id
remove `dau_`

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_ecs_cluster.tf
> +  task_definition = aws_ecs_task_definition.dau_xss_task_definition.arn
remove `dau_`

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_taskdefinition.tf
> +# creates the XSS task definition. container definition is defined in the service.json file
recommend renaming file to `aws_xss_task_definition.tf`

2021-02-03 00:17 UTC, mattdrayer commented on aws_xss_taskdefinition.tf
> +  container_definitions = file("task-definitions/dauxssimages.json")
remove `dau` -> `xss_images.json`

2021-02-03 00:17 UTC, mattdrayer commented on iamrole.tf
> +resource "aws_iam_role" "ecs_task_role" {
rename file to `aws_iam_role.tf`, yes?

2021-02-03 00:17 UTC, mattdrayer commented on iamrole.tf
> +    Name = "ecs role"
Not sure if it matters, but should `Name` be lowercase or in the current case format?

2021-02-03 00:17 UTC, mattdrayer commented on task-definitions/dauxiaimages.json
> +[
Rename file to xia_dau_images.json

2021-02-03 00:17 UTC, mattdrayer commented on task-definitions/dauxiaimages.json
> +      "image":"jmdiouf/openlxp-xia-dau:latest",
at some point we'll need to reference a more official image than Mac's.

2021-02-03 00:17 UTC, mattdrayer commented on task-definitions/dauxisimages.json
> +[
rename to `xis_images.json`

2021-02-03 00:17 UTC, mattdrayer commented on task-definitions/dauxssimages.json
> +[
rename to `xss_images.json`

2021-02-03 00:17 UTC, mattdrayer commented on task-definitions/dauxssimages.json
> +      "image":"jmdiouf/openlxp-xia-dau:latest",
I think we need to reference a different image here -- perhaps `jmdiouf/openlxp-xss:latest`

2021-02-03 00:17 UTC, mattdrayer commented on task-definitions/dauxisimages.json
> +      "image":"jmdiouf/openlxp-xia-dau:latest",
I think we need to reference a different image -- `jmdiouf/openlxp-xis:latest`, yes?

2021-02-03 00:17 UTC, mattdrayer commented on task-definitions/xse_elasticsearchimage.json
> +  {
Recommend renaming file to `xse_images.json`, or possibly `xse_images_elasticsearch.json`

2021-02-03 00:17 UTC, mattdrayer commented on variables.tf
> +variable "profile" {
For my own understanding, why would we add an entry to this file, versus embedding the information directly in the TF script. Is it for reuse across scripts?  Operator-specified overrides?

2021-02-03 13:15 UTC, micson-us commented on task-definitions/dauxssimages.json
> +      "image":"jmdiouf/openlxp-xia-dau:latest",
Hey Matt - I agree. I just have this as a place holder until we have specific component images created and pushed.

2021-02-03 13:17 UTC, micson-us commented on variables.tf
> +variable "profile" {
Yup it is for reuse across scripts however, as I made updates to the scripts, I do not think I am calling these variables. I can plan on removing this file or adding more redundant entries to the variables and use that across scripts.

2021-02-03 13:18 UTC, micson-us commented on aws_xis_taskdefinition.tf
> +  family                = "dau_xis_task_definition"
Thanks for catching these!! made copies of the original XIA script and missed updating those

2021-02-03 14:59 UTC, mattdrayer commented on variables.tf
> +variable "profile" {
ok sounds good -- I like the idea of a variables file for information that is shared across scripts.  It's easy to go overboard and make everything a shared variable even if it's not actually shared, so we'll just want to be sure we only generalize things that are truly shared.

2021-02-03 20:42 UTC, mattdrayer commented on aws_xia_task_definition.tf
> +  container_definitions = file("task-definitions/dau_xia_images.json")
`xia_dau_images.json`

2021-03-01 17:09 UTC, mattdrayer commented on aws_xia_task_definition.tf
> +  family                = "xia_dau_task_definition"
It seems we have some XIA-related files that have to do with all XIAs, and some that have to do with the DAU XIA.  Is the goal to have all XIA AWS resources managed within the same set of XIA files, or will each XIA have its own files.  For example, should the name of this file be `aws_xia_task_definition.tf` or `aws_xia_dau_task_definition.tf`?

2021-03-01 17:11 UTC, mattdrayer approved these changes
One comment regarding general XIA scripts versus specific XIA scripts (eg, DAU XIA vs. EDX XIA).  If we can resolve that then I am good with merging what we have to `main`.

2021-03-03 20:57 UTC, micson-us commented on aws_xia_task_definition.tf
> +  family                = "xia_dau_task_definition"
I think they should have separate task definitions so the name should be 'aws_xia_dau_task_definition.tf', 'aws_xia_jko_task_definition.tf', 'aws_xia_edx_task_definition.tf', etc. Thanks for catching that!

2021-03-03 21:12 UTC, mattdrayer commented on aws_xse_taskdefinition.tf
> +# creates the XIA task definition. container definition is defined in the service.json file
file name -> `aws_xse_task_definition.tf`

2021-03-03 21:13 UTC, mattdrayer commented on aws_xss_taskdefinition.tf
> +# creates the XSS task definition. container definition is defined in the service.json file
file name -> `aws_xss_task_definition.tf`

2021-03-03 21:13 UTC, mattdrayer commented on aws_xss_taskdefinition.tf
> +# creates the XSS task definition. container definition is defined in the service.json file
Oh, wait, I'm seeing that file name above -- what's the difference between these two files?

2021-03-03 21:15 UTC, mattdrayer commented on task-definitions/dau_xia_images.json
> +[
file name -> `xia_dau_images.json`

2021-03-04 17:20 UTC, mattdrayer approved these changes

2021-03-04 19:13 UTC, jdiouf approved these changes

2021-03-04 20:06 UTC, merged